sudo: false
language: generic
matrix:
  include:
  - os: linux
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_install:
- bash ./utilities/travis_setup.sh
- export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
- latexmk -pdf -interaction=nonstopmode -halt-on-error kulumani_cv.tex
after_success:
- bash ./utilities/deploy.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: kulumani_cv.pdf
  skip_cleanup: true
  on:
    repo: skulumani/kulumani_cv
    branch: master
    tags: true
env:
  global:
    secure: YQnQogRzwzhSRj/GfoZdbc843FLNqUKQNN0/zRv6G6iP/TFXrFKAzaeq+pC4Ox2cBjRtAakUTrBosWaBAf8n50c7luqfGnfIbiCxy/EzGXJMb9BcWowemtENG3fCIJ6sIr6TxIVqUuIxvTNpE6Xb0b83SO1m9Iogrg7dBpSlhp9M9McvlU4a7HzpZdSIiK9KWtwdIPU2WvituMzxdY8a08l72DEulndYOIRyWThdNjlhG+nAuEuOQHP8o5oMQw/s7PPy6m5G/PvtPodNB57cUlg0Q8j9s8s5mUEVQLJILslwBQ2P4MK6VoTfDfTKLIHjZYQEwIh07RH7ibMvRlSer1VG02IYmE9tNKzKr70TVweGxtnZUvkgnD4ZsZCMhUWfPTRCiEDpPirTOD6YarVGo3RFNHPBzUwM1ME0g17AoaELzNkXwiFnjg3LwRdmFMjuvYdQccGy1Gd+WF1FOMjvzjOpc9EYnT9TIURHqi8eDO0u735SFUrr+7EizzpQUo/9haeJBpcY9uTebN92v4F0E7xXGyPyjJvpSvMaKnrtSfvM5UmOmc1HeyKYSloKZyc4d8gmZOdWfrn9WeD/GQFPUUvfcnbcbwJTu3Ibef/sXm7wEZugpS4ObG/l5exgsEwif9sxokcLeCRcXP+bZWnFcCcu7Nu5xrDMkxAllKH3iOU=
